name: base
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - fastq-screen
  - picard
  - trimmomatic
  - bwa
  - samtools
  - vcftools
  - bcftools
  - gatk4
  - sra-tools
  - ffq
  - nextflow
  - nf-core
